[tool.poetry]
name = "testing-python"
version = "0.1.0"
description = ""
authors = ["shahdivyank <divyank.shah.2016@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
